### ISSUE TITLE
RPC updates to improve debugging of staking and voting

### ISSUE THREAD

**Issue by pgerzani** [projectpai/paicoin#327]
Currently, it is difficult to investigate the causes of missed tickets and votes.  To fix this, I'm thinking we can make the following changes:

1. `livetickets` should have two new options:
 - A 'my wallet only' filter option, (default to true perhaps?) to only include tickets for my wallet vs. the whole network 
 - A verbose option, like when you do `getblock`.  If verbose is > 0, then it should show additional data for missed tickets like:
```json
{
  "tickets": [
    {
      "txid": "539513d00d7088157ae9635f88853447f4a5706fcb9bf009274dc4a52ef3c1bd",
      "fee":0.0200,
      "purchase_height": 78700,
      "mature": true
    },
    {
      "txid": "a15688bd91dafa7630410772f2189d97485fc29298028c1213acb4fc564e76eb",
      "fee":0.0200,
      "purchase_height": 78000,
      "mature": false
    }
  ]
}
```
1. `missedtickets` should have two new options: 
 - A 'my wallet only' filter option, (default to true perhaps?) to only include tickets for my wallet vs. the whole network 
 - A verbose option, like when you do `getblock`.  If verbose is > 0, then it should show additional data for missed tickets like:
```json
{
  "tickets": [
    {
      "txid": "539513d00d7088157ae9635f88853447f4a5706fcb9bf009274dc4a52ef3c1bd",
      "fee":0.0200,
      "purchase_height": 78700,
      "cause":"missed_vote",
      "missed_height": 78850
    },
    {
      "txid": "a15688bd91dafa7630410772f2189d97485fc29298028c1213acb4fc564e76eb",
      "fee":0.0200,
      "cause":"expiration",
      "purchase_height": 78000,
      "missed_height": null
    }
  ]
}
```
1. `winningtickets` should have an optional parameter for the blockheight to get the winning list from, defaulting to the current block height

**Comment by bambache** [comment]
Currently we have some RPC implemented in rpcwallet.cpp for category Wallet:
 - `gettickets`, having a required boolean argument `includeimmature` which is "Returning the hashes of the tickets currently owned by wallet."
 - `listtickets`, having no arguments, which "Produces an array of ticket information objects." -> this is not implemented as, at some point, it disappeared from Decred's repo -> we need to delete it.

In the mining.cpp we have some RPCs for category Mining:
 - `livetickets`, no args, returns live ticket hashes from the chain tip's stakenode object
 - `missedtickets`, no args, returns missed ticket hashes from the chain tip's stakenode object
 - `winningtickets`, no args, returns winning ticket hashes from the chain tip's stakenode object -> I added this for debugging / functional-testing (before autovoting) purposes and is **not present in Decred**, it might even pose security issues.

I would not access the wallet from mining.cpp, I would rather expose some information in `gettickets` by accessing the stakenode on the tip. Otherwise, I agree with the verbose option on `livetickets` and `missedtickets`, I should probably add it also for `gettickets`.
I would also add the blockheight parameter on `livetickets` and `missedtickets`, it might be useful.
What do you think?
