### ISSUE TITLE
About Paicoin and Bitcoin

### ISSUE THREAD

**Issue by ZexiFangkong** [projectpai/paicoin#34]
HI, @projectpaiadmin 
     Why did you delete my previous two questions?
     What does your project have to do with BitCoin?
     I think your source code almost copied someone's BitCoin.
     Must be a guilty conscience afraid of being exposed.

**Comment by ZexiFangkong** [comment]
Hi, @projectpaiadmin  Please reply if you are free.

**Comment by ZexiFangkong** [comment]
@projectpaiadmin

**Comment by projectpaiadmin** [comment]
Your questions were not deleted; they are still visible under "Closed" issues. These issues were closed because GitHub Issues is not a forum; it is specifically for reporting bugs and technical problems with the code. Project PAI encourages you to join some or all of the following communities to engage in further non-technical discussion. Chinese, Japanese and Korean communities are also available.

Telegram: https://t.me/projectpai
Twitter: https://twitter.com/projectpai
Facebook: https://www.facebook.com/projectpai
Linkedin: https://www.linkedin.com/company/projectpai/
Medium: https://medium.com/project-pai
Youtube: https://www.youtube.com/c/projectpai

**Comment by ZexiFangkong** [comment]
The main thing is that I think if you are really a credible, good project, from the perspective of technology development, at least your source code implementation should be more independent and innovative. You can learn from the great project BitCoin, but it is not much different from plagiarism, which makes me very disappointed.

**Comment by projectpaiadmin** [comment]
Refer to Project PAI's response [here](https://github.com/projectpai/paicoin/issues/35).

**Please join the Telegram channels to engage in further non-technical discussion. GitHub Issues is not a forum.**

English: https://t.me/projectpai
Chinese: https://t.me/projectpaiCN
Korean: https://t.me/ProjectPAIKoreaOFFICIAL
Japanese: https://t.me/ProjectPAIJapanOFFICIAL
