### ISSUE TITLE
Investigate handling of mempool at significant size

### ISSUE THREAD

**Issue by pgerzani** [projectpai/paicoin#343]
Now that the mempool is of substantial size, I have some questions/concerns I'd like researched:

1. What is the max size of the mempool for a given paicoind instance?  Is this configurable and if so, what is the default?
2. How long will a node allow a transaction to remain in the mempool?  Is this configurable and if so, what is the default?
3. Once a transaction is in the mempool, what options does a node have to recover those funds?  (For example a ticket that is never included in a block)
4.  How do the ancestor attributes you mentioned in our call today impact the mempool?
5. Any other concerns with the size of the mempool that you can think of?

**Comment by bambache** [comment]
1. There is the -maxmempool flag: "Keep the transaction memory pool below <n> megabytes". Its default is 300MB.
2. Flag "-mempoolexpiry" allows setting a time limit "Do not keep transactions in the mempool longer than <n> hours". Defaults to 336 hours (2 weeks).
3. The size and expiry flags above determine if a transaction is dropped from the mempool. In LimitMempoolSize function, expired transactions are removed from mempool along with their descendants. Also transactions are trimmed until the mempool size fits the size limit. This mechanism applies to every transaction, so the same applies to a ticket that is never included in a block.
4. There are several flags that limit the acceptance of a transaction in mempool:
- limitancestorcount - "Do not accept transactions if number of in-mempool ancestors is <n> or more", default is 25
- limitancestorsize - "Do not accept transactions whose size with all in-mempool ancestors exceeds <n> kilobytes", default is 101 kB
- limitdescendantcount - "Do not accept transactions if any ancestor would have <n> or more in-mempool descendants", default is 25
- limitdescendantsize - "Do not accept transactions if any ancestor would have more than <n> kilobytes of in-mempool descendants", default is 101kB
AcceptToMemoryPoolWorker uses CalculateMemPoolAncestors to determine if an incoming transactions exceeds the above limits, if that is the case it will reject it with "too-long-mempool-chain".
My concern was that a vote might get rejected from entering the mempool when one of those limits is exceeded, and since getblocktemplate is sensible to what the mempool holds it might lead to a "too-few-votes" error.
5. There are other flags that could limit the synchronization of mempool from node to node:
 - feefilter - "Tell other nodes to filter invs to us by our mempool min fee", default is true
 - minrelaytxfee - "Fees (inPAI/kB) smaller than this are considered zero fee for relaying, mining and transaction creation", default is 0.00001
