### ISSUE TITLE
You should not close my issues

### ISSUE THREAD

**Issue by ZexiFangkong** [projectpai/paicoin#35]
Hello, @projectpaiadmin  Because you replied too slowly, And shut down two of my problems.
     I thought it was irresponsible of you to shut it down without replying.
     I just saw your reply today.
     But I'm not particularly pleased with your reply.
     1. Pai According to the white paper, it should be in the area of artificial intelligence, based on blockchain.But I don't think you found this in the source code you modified. So it's very suspicious.
     2. You're an innovative project, so why would the source code need to copy BitCoin so much? It's not as innovative as you describe it. Let me down。
     3. BitCoin is a great project to borrow from, but I'm sorry to trust your people。

**Comment by ZexiFangkong** [comment]
@projectpaiadmin  Hey. Please reply if you are free.

**Comment by ZexiFangkong** [comment]
@projectpaiadmin

**Comment by projectpaiadmin** [comment]
Project PAI implores you to read the [technical white paper](https://static.projectpai.com/whitepaper-tech.pdf), the components of which have been fully implemented in the Project PAI repositories. One of the key innovations described in this white paper is **Section 2.3: Data**. The implementation of this data storage layer can be found [here](https://github.com/projectpai/paicoin/tree/master/contrib/data-share); its corresponding technical description is available under PAI Coin Development Proposal (PDP) 2, [here](https://github.com/projectpai/pdps/blob/master/pdp-0002.mediawiki).

Leading US Artificial Intelligence company, [ObEN](https://oben.me), is one of the first adopters of the Project PAI blockchain. The data storage layer enabled by PAI Coin provides many benefits for secure storage of sensitive data related to Personal AI technology. However, much of ObEN's AI technology is proprietary and will not be visible in these open-source repositories.

Your issues were closed because GitHub Issues is not a forum; it is specifically for reporting bugs and technical problems with the code. Project PAI encourages you to join some or all of the following communities to engage in further non-technical discussion. Chinese, Japanese and Korean communities are also available.

Telegram: https://t.me/projectpai
Twitter: https://twitter.com/projectpai
Facebook: https://www.facebook.com/projectpai
Linkedin: https://www.linkedin.com/company/projectpai/
Medium: https://medium.com/project-pai
Youtube: https://www.youtube.com/c/projectpai

**Comment by ZexiFangkong** [comment]
thank you.
But I'm still a little confused.
Do you mean that PaiCoin is based on the BitCoin source code implementation, mainly for sensitive data, artificial intelligence aspects of innovative modifications introduced into the project?
The main implementation is in Section 2.3: Data, right

**Comment by WhisperKarl** [comment]
its just a scam .. LOL

**Comment by projectpaiadmin** [comment]
@ZexiFangkong PAI Coin is a Bitcoin code fork, similar to several other widely known cryptocurrencies. The primary initial innovation of Project PAI is the addition of a data storage layer, described in Section 2.3 of the [Technical White Paper](https://static.projectpai.com/whitepaper-tech.pdf). Further innovations are in progress according to the following short-term quarterly milestones.

- **Q3 2018 (July - September)**
WeChat mini-program wallet
PAI Up Desktop wallets (Windows/macOS)
Smart contract and token support
- **Q4 2018 (October - December)**
Test Proof of Useful Work (PoUW) protocol with early adopters
- **Q1 2019 (January - March)**
Dedicated chip development for PAI

**Please join the Telegram channels to engage in further non-technical discussion. GitHub Issues is not a forum.**

English: https://t.me/projectpai
Chinese: https://t.me/projectpaiCN
Korean: https://t.me/ProjectPAIKoreaOFFICIAL
Japanese: https://t.me/ProjectPAIJapanOFFICIAL
